// Copyright (c) 2018 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(k){var e,b={_breaker:{},_start:null,each:function(){var a,c=function(c,f){return c===b._breaker||Boolean(f)&&b.elapsed()>a};return function(d,f,h){var e,m;m=b.type(d);if(1===arguments.length)a=arguments[0];else if(h=b.extend({timeout:!1},h),"object"===m&&d.hasOwnProperty)for(e in d){if(d.hasOwnProperty(e)&&c(f(d[e],e),h.timeout))break}else if(d){e=0;for(m=d.length;e<m&&!c(f(d[e],e),h.timeout);e++);}}}(),extend:function(a){var c,d,b,h,e=arguments.length;a=a||{};for(d=1;d<e;d++)if(h=arguments[d],
void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(c,a){try{return("function"===typeof window[a]||"object"===typeof window[a])&&c instanceof window[a]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in
c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var d="array"===b.type(a)?[]:{};b.each(a,function(a,h){c(a,h)&&("array"===b.type(d)?d.push(a):d[h]=a)});return d},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},apiCallback:function(a,c){return function(d){"string"===b.type(d)&&(d={response:[d]});a.apply(c,d.response.concat(d.data))}},
attributes:function(a,c){var d;c=c||{};for(d in c)"function"===b.type(a.setAttribute)?a.setAttribute(d,c[d]):a["class"===d?"className":d]=c[d]},attrValues:function(a,c,b){return(c=a[c])&&c.split?c.split(b||" "):[]},batchable:function(a,c){c=c||b.noop;var d=function(){return b.extend({batch:!0,timeout:100},c())},f=b.traits.cors&&b.traits.json,h=[],e=null,m=function(){null!==e&&(clearTimeout(e),e=null);1===h.length?a.apply(null,h[0].arguments):1<h.length&&a.apply(null,h);h=[]},g=function(){h.push({arguments:b.toArray(arguments),
batch:!0});!f||!d().batch?m():null===e&&(e=setTimeout(b.entryPoint(b.bind(function(){m()},this)),d().timeout))};b.extend(g,{flush:m,now:a});return g},batchArgs:function(a,c){return b.map(a,function(a){return void 0===c?a.arguments:a.arguments[c]})},batchCallType:function(a){var c;return b.reduce(null,a,function(a,b){c=b[0];return null!==a&&c!==a?"batch":c})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(a){return"object"===b.type(a)&&a.batch&&"array"===b.type(a.arguments)}).length===
a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(f,h,e){if(f){var m=f[c];if(m||void 0!==e)return m||(m=++b),a[m]||(f[c]=m,a[m]={}),void 0!==e&&(a[m][h]=e),"string"===typeof h?a[m][h]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},
a)},commonParams:function(a,c){var d;c=c||{};d={drKey:c.key?null:c.dr_key,key:c.key,libId:c.library_id,subId:c.sub_id};("click"===a||"ping"===a)&&b.extend(d,{cuid:c.cuid,loc:location.href,v:1},d);return d},contains:function(a,c,d){return Boolean(b.find(a,function(a){return a===c},d))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==
b;)if(b=b.parent,b===c)return!0;return!1},cors:function(a,c,d){var f;f=new window.XMLHttpRequest;f.onreadystatechange=function(){if(4===f.readyState&&200===f.status){var a=b.noop,c=[],h;if(d)d(f.responseText);else if("string"===b.type(f.responseText)&&(h=f.responseText.match(/^\s*(?:\/\*\*\/)?([^(\s]+)\s*\((.*)\);?\s*$/)))a=h[1].replace(/(^\s+|\s+$)/g,""),c=b.fromJSON("["+h[2]+"]"),window[a].apply(window,c)}};try{return f.open("POST",a),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),
f.withCredentials=!0,f.send(c),!0}catch(h){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,f){a=(f||document).createElement(a);b.attributes(a,c);b.css(a,d);return a},css:function(a,c){var b;c=c||{};for(b in c)try{a.style[b]=c[b]}catch(f){}return a},destructing:function(a){return function(a){var b=!1,f;return function(){b||(f=a.apply(null,arguments),b=!0);return f}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():
0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(f){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},every:function(a,c){return Boolean(!b.some(a,function(a){return!c(a)}))},
exceptionLogger:function(){var a=!1,c=b.noop;return function(b,f){if(void 0!==f)a=f,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(f){c(f)}else return b.apply(this,arguments)}}}(),find:function(a,c,d){var f;b.each(a,function(a,d){if(c(a,d))return f=a,b._breaker},d);return f},generateNodeFilter:function(){var a=function(a,b){var h,e;b=","+b.join(",")+",";h=0;for(e=a.length;h<e;h++)if(c(a[h],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=
b.extend({custom:null,classes:[],rels:[],selectors:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");b.isArray(d.selectors)&&(d.selectors=d.selectors.join(","));return function(f,h){h=b.extend({ancestors:!0,self:!0},h);var e=function(f,h){var e;if(e=!(d.tags&&d.tags.length&&c(f.nodeName.toLowerCase(),d.tags))){if(e=d.classes)if(e=d.classes.length){e=d.classes;var l=b.attrValues(f,"className");e=a(e,l)}if(e=!e){if(e=d.rels)if(e=d.rels.length)e=d.rels,l=b.attrValues(f,"rel"),
e=c(f.nodeName.toLowerCase(),",a,")&&a(e,l);e=!e&&!(d.selectors&&d.selectors.length&&b.matches(f,d.selectors))&&!("function"===b.type(d.custom)&&d.custom(f,h))}}return e};if(h.self&&!e(f,!0))return!1;if(h.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!e(f,!1))return!1;return!0}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");
c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,f=Infinity,e=-Infinity,l=-Infinity,m;for(a=0;a<c;a++)m=b.position(arguments[a]),d=Math.min(d,m.x),f=Math.min(f,m.y),e=Math.max(e,m.x+arguments[a].offsetWidth),l=Math.max(l,m.y+arguments[a].offsetHeight);return{x:d,y:f,w:e-d,h:l-f,x1:d,y1:f,x2:e,y2:l}},getActualHref:function(a){return b.cache(a,"href")||a.href},hasAttrValue:function(a,c,d,f){return c?b.contains(b.attrValues(a,c,
f),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},isVisible:function(a){return Boolean(a.offsetHeight||a.offsetWidth||!a.getClientRects||a.getClientRects().length)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},links:function(){var a=["http:","https:"],c=function(c,f){return b.all(c,function(c){return c.href&&(!f.filter_by_scheme||b.contains(a,c.protocol))&&(!f.filter_homepages||"/"!==c.pathname)&&(!f.filter_internal||c.hostname!==b.context(c).location.hostname)})};return function(a,f,e){e=b.extend({filter_homepages:!0,filter_internal:!0,filter_by_scheme:!0},e);f=b.map(f.split(","),function(a){return a+" a[href]"}).join(",");
return c(b.withScope(a,f,{ancestors:!1,consolidate:!0}),e)}}(),map:function(a,c,d){return b.reduce([],a,function(a,b,d){a.push(c(b,d));return a},d)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(d){return!0}},mergeable:function(a){var c=function(){return b.extend({batchable:!0,batchFn:b.noop,nonBatchFn:b.noop,timeout:100},a())};return b.batchable(function(){b.batched(arguments)?c().batchable?b.each(b.batchArgs(arguments),function(a){c().batchFn.apply(this,
a)}):c().nonBatchFn.apply(this,arguments):c().nonBatchFn.apply(this,arguments)},function(){return{batch:!0,timeout:c().timeout}})},mergeParams:function(a){var c,d,f,e=arguments.length,l=function(d,f){c=a[f];a.hasOwnProperty(f)&&b.isArray(d)&&b.isArray(c)?a[f]=b.unique(c.concat(d)):a[f]=d};for(d=1;d<e;d++)f=arguments[d],b.each(f,l);return b.prune(a)},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,
d,f){var e,l,m;if(1===arguments.length)a=c;else{if(2===arguments.length){if(!a)return;f=d;d=c;c=a}else e=b.toArray(arguments).slice(3,arguments.length);try{l=c["on"+d]}catch(g){}"function"===typeof l&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=l.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));m=b.entryPoint(function(){if(a.enabled())return f.apply(null,
b.toArray(arguments).concat(e||[]))});c.addEventListener?c.addEventListener(d,m,!1):c.attachEvent&&c.attachEvent("on"+d,m)}}}(),packageArgs:function(){return b.toArray(arguments)},position:function(a,c){var d,f=0,e=0,l=0,m=0;c=c||document;if(!b.isInDom(a))return!1;d=a;do f+=d.offsetLeft,e+=d.offsetTop,d=d.offsetParent;while(d);d=a;do l+=d.scrollLeft,m+=d.scrollTop,d=d.parentNode;while(d&&d!==c.body);return{x:f-l,y:e-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=
!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});return a},ready:function(){var a=!1,c=[],d=!1,f,e,l,m,g;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,!1);g()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),g())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return g();if(document.addEventListener)document.addEventListener("DOMContentLoaded",
l,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&e()}b.on(window,"load",g)}};e=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(e),1);return}g()}};g=function(){if(!d){if(!document.body)return setTimeout(b.entryPoint(g),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){f();d?a():c.push(a)}}(),reduce:function(a,c,
d,f){b.each(c,function(c,b){a=d(a,c,b)},f);return a},reformatKeys:function(a){var c,d,f=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,f),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,f,e=b.attrValues(a,"className");d=0;for(f=e.length;d<f;d++)e[d]===c&&delete e[d];a.className=e.join(" ")}},request:function(a,c,d){var f,e,l,g=b.uniqid("vglnk_"),p=b.toArray(arguments).slice(3,
arguments.length),n=function(a,c,d){var f={},e=!!c.length,h=!0===d||!1===d;if(e||h)a=b.createA(a),e&&(f.search="?"+c),h&&(c=a.protocol||b.context(a).location.protocol||"http:",f.protocol=c.replace(/s?:$/,function(){return d?"s:":":"})),a=b.extend(a,f).href;return a};e=function(a,c){var d={},f=b.commonParams();d[c]={};b.each(a,function(a,b){b in f?d[b]=a:d[c][b]=a});d[c]=b.toJSON(d[c]);return b.prune(d)};d=b.extend({fn:b.noop,json_payload:null,jsonp:!0,"return":!1,ssl:null,timeout:null},d);"string"===
typeof d.fn?(f=window[d.fn],g=d.fn):"function"===typeof d.fn&&(f=d.fn);"function"===b.type(f)&&(l=b.entryPoint(b.destructing(function(){var a,e;d.json_payload&&(e=d.json_payload,a=b.fromJSON(c[e]),c=b.extend(c,a),delete c[e]);f({response:b.toArray(arguments),data:p,args:c});window[g]&&(window[g]=void 0)})),null!==d.timeout&&setTimeout(l,d.timeout));d.json_payload&&b.traits.cors&&(c=e(c,d.json_payload));!0===d.jsonp&&(window[g]=l,c=b.extend({format:"jsonp",jsonp:g},c));e=b.toQuery(c);return d["return"]?
n(a,e,d.ssl):b.traits.json&&b.traits.cors&&b.cors(n(a,"",d.ssl),e,d.jsonp?null:l)?!0:b.jsonp(n(a,e,d.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},some:function(a,c){return Boolean(b.find(a,function(a){return c(a)}))},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},time:function(){return(new Date).getTime()},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,
f,e=[];b=0;for(f=a.length;b<f;b++)e[b]=a[b];return e}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,d){b.contains(a,d)||a.push(d);
return a})},unlink:function(a){var c,b=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)b.appendChild(c);a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a)}},withScope:function(){var a=function(a,d,f){if(f.self&&b.contains(d,a,{timeout:!0}))return a;if(f.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(d,a,{timeout:!0})},{timeout:!0})};return function(c,d,f){var e,l=b.select(d);f=b.extend({ancestors:!0,consolidate:!1,descendants:!0,
self:!0},f);f.descendants&&(e=b.map(l,function(a){return[a,b.ancestors(a)]},{timeout:!0}));c=b.all(b.map(c,function(c){var d,g=[];(d=a(c,l,f))?g.push(d):1===c.nodeType&&f.descendants&&b.each(e,function(a){var d=a[0];b.contains(a[1],c,{timeout:!0})&&g.push(d)},{timeout:!0});return[c,g]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?b.unique(b.reduce([],c,function(a,c){return a.concat(c[1])},{timeout:!0})):c}}()});var q=function(){var a=b.find(b.toArray(arguments),
function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};q.amd=!0;(function(a){function c(a,b,c,d){var f,e,h,g,l;(b?b.ownerDocument||b:C)!==z&&J(b);b=b||z;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(g=b.nodeType)&&9!==g)return[];if(F&&!d){if(f=oa.exec(a))if(h=f[1])if(9===g)if((e=b.getElementById(h))&&e.parentNode){if(e.id===h)return c.push(e),c}else return c;else{if(b.ownerDocument&&(e=b.ownerDocument.getElementById(h))&&T(b,e)&&e.id===h)return c.push(e),c}else{if(f[2])return K.apply(c,
b.getElementsByTagName(a)),c;if((h=f[3])&&x.getElementsByClassName&&b.getElementsByClassName)return K.apply(c,b.getElementsByClassName(h)),c}if(x.qsa&&(!A||!A.test(a))){e=f=y;h=b;l=9===g&&a;if(1===g&&"object"!==b.nodeName.toLowerCase()){g=U(a);(f=b.getAttribute("id"))?e=f.replace(pa,"\\$&"):b.setAttribute("id",e);e="[id='"+e+"'] ";for(h=g.length;h--;)g[h]=e+E(g[h]);h=ca.test(a)&&s(b.parentNode)||b;l=g.join(",")}if(l)try{return K.apply(c,h.querySelectorAll(l)),c}catch(m){}finally{f||b.removeAttribute("id")}}}return ga(a.replace(Y,
"$1"),b,c,d)}function b(){function a(b,d){c.push(b+" ")>t.cacheLength&&delete a[c.shift()];return a[b+" "]=d}var c=[];return a}function f(a){a[y]=!0;return a}function e(a){var b=z.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function l(a,b){for(var c=a.split("|"),d=a.length;d--;)t.attrHandle[c[d]]=b}function g(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ha)-(~a.sourceIndex||ha);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===
b)return-1;return a?1:-1}function p(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function n(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function w(a){return f(function(b){b=+b;return f(function(c,d){for(var f,e=a([],c.length,b),h=e.length;h--;)if(c[f=e[h]])c[f]=!(d[f]=c[f])})})}function s(a){return a&&typeof a.getElementsByTagName!==Q&&a}function r(){}function E(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;
return d}function v(a,b,c){var d=b.dir,f=c&&"parentNode"===d,e=qa++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||f)return a(b,c,e)}:function(b,c,h){var X,g,l=[D,e];if(h)for(;b=b[d];){if((1===b.nodeType||f)&&a(b,c,h))return!0}else for(;b=b[d];)if(1===b.nodeType||f){g=b[y]||(b[y]={});if((X=g[d])&&X[0]===D&&X[1]===e)return l[2]=X[2];g[d]=l;if(l[2]=a(b,c,h))return!0}}}function k(a){return 1<a.length?function(b,c,d){for(var f=a.length;f--;)if(!a[f](b,c,d))return!1;return!0}:a[0]}function u(a,
b,c,d,f){for(var e,h=[],g=0,l=a.length,m=null!=b;g<l;g++)if(e=a[g])if(!c||c(e,d,f))h.push(e),m&&b.push(g);return h}function B(a,b,d,e,h,g){e&&!e[y]&&(e=B(e));h&&!h[y]&&(h=B(h,g));return f(function(f,g,l,m){var r,v,p=[],w=[],n=g.length,k;if(!(k=f)){k=b||"*";for(var s=l.nodeType?[l]:l,E=[],P=0,W=s.length;P<W;P++)c(k,s[P],E);k=E}k=a&&(f||!b)?u(k,p,a,l,m):k;s=d?h||(f?a:n||e)?[]:g:k;d&&d(k,s,l,m);if(e){r=u(s,w);e(r,[],l,m);for(l=r.length;l--;)if(v=r[l])s[w[l]]=!(k[w[l]]=v)}if(f){if(h||a){if(h){r=[];for(l=
s.length;l--;)if(v=s[l])r.push(k[l]=v);h(null,s=[],r,m)}for(l=s.length;l--;)if((v=s[l])&&-1<(r=h?N.call(f,v):p[l]))f[r]=!(g[r]=v)}}else s=u(s===g?s.splice(n,s.length):s),h?h(null,g,s,m):K.apply(g,s)})}function da(a){var b,c,d,f=a.length,e=t.relative[a[0].type];c=e||t.relative[" "];for(var h=e?1:0,l=v(function(a){return a===b},c,!0),g=v(function(a){return-1<N.call(b,a)},c,!0),m=[function(a,c,d){return!e&&(d||c!==Z)||((b=c).nodeType?l(a,c,d):g(a,c,d))}];h<f;h++)if(c=t.relative[a[h].type])m=[v(k(m),
c)];else{c=t.filter[a[h].type].apply(null,a[h].matches);if(c[y]){for(d=++h;d<f&&!t.relative[a[d].type];d++);return B(1<h&&k(m),1<h&&E(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(Y,"$1"),c,h<d&&da(a.slice(h,d)),d<f&&da(a=a.slice(d)),d<f&&E(a))}m.push(c)}return k(m)}function ra(a,b){var d=0<b.length,e=0<a.length,h=function(f,h,l,g,m){var r,v,w,p=0,s="0",n=f&&[],k=[],E=Z,P=f||e&&t.find.TAG("*",m),W=D+=null==E?1:Math.random()||0.1,na=P.length;for(m&&(Z=h!==z&&h);s!==na&&null!=(r=
P[s]);s++){if(e&&r){for(v=0;w=a[v++];)if(w(r,h,l)){g.push(r);break}m&&(D=W)}d&&((r=!w&&r)&&p--,f&&n.push(r))}p+=s;if(d&&s!==p){for(v=0;w=b[v++];)w(n,k,h,l);if(f){if(0<p)for(;s--;)!n[s]&&!k[s]&&(k[s]=sa.call(g));k=u(k)}K.apply(g,k);m&&(!f&&0<k.length&&1<p+b.length)&&c.uniqueSort(g)}m&&(D=W,Z=E);return n};return d?f(h):h}var R,x,t,$,ia,U,ea,ga,Z,L,S,J,z,G,F,A,O,aa,T,y="sizzle"+-new Date,C=a.document,D=0,qa=0,ja=b(),ka=b(),la=b(),fa=function(a,b){a===b&&(S=!0);return 0},Q="undefined",ha=-2147483648,
ta={}.hasOwnProperty,M=[],sa=M.pop,ua=M.push,K=M.push,ma=M.slice,N=M.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},Y=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,va=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,wa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,xa=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,ya=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
za=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Aa=/^(?:input|select|textarea|button)$/i,Ba=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,oa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ca=/[+~]/,pa=/'|\\/g,H=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,I=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{K.apply(M=ma.call(C.childNodes),C.childNodes),M[C.childNodes.length].nodeType}catch(Ca){K={apply:M.length?function(a,b){ua.apply(a,ma.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}x=c.support={};ia=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};J=c.setDocument=function(a){var b=a?a.ownerDocument||a:C;a=b.defaultView;if(b===z||9!==b.nodeType||!b.documentElement)return z;z=b;G=b.documentElement;F=!ia(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){J()},!1):a.attachEvent&&a.attachEvent("onunload",function(){J()}));x.attributes=e(function(a){a.className="i";return!a.getAttribute("className")});
x.getElementsByTagName=e(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});x.getElementsByClassName=V.test(b.getElementsByClassName)&&e(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});x.getById=e(function(a){G.appendChild(a).id=y;return!b.getElementsByName||!b.getElementsByName(y).length});x.getById?(t.find.ID=function(a,b){if(typeof b.getElementById!==Q&&F){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},t.filter.ID=function(a){var b=a.replace(H,I);return function(a){return a.getAttribute("id")===b}}):(delete t.find.ID,t.filter.ID=function(a){var b=a.replace(H,I);return function(a){return(a=typeof a.getAttributeNode!==Q&&a.getAttributeNode("id"))&&a.value===b}});t.find.TAG=x.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==Q)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],f=0,e=b.getElementsByTagName(a);if("*"===a){for(;c=
e[f++];)1===c.nodeType&&d.push(c);return d}return e};t.find.CLASS=x.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==Q&&F)return b.getElementsByClassName(a)};O=[];A=[];if(x.qsa=V.test(b.querySelectorAll))e(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),e(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(x.matchesSelector=V.test(aa=G.matches||G.webkitMatchesSelector||G.mozMatchesSelector||G.oMatchesSelector||G.msMatchesSelector))&&
e(function(a){x.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");O.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));O=O.length&&RegExp(O.join("|"));
T=(a=V.test(G.compareDocumentPosition))||V.test(G.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};fa=a?function(a,c){if(a===c)return S=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!x.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===C&&T(C,a)?-1:c===b||c.ownerDocument===C&&T(C,c)?1:L?N.call(L,a)-N.call(L,c):0:d&4?-1:1}:function(a,c){if(a===c)return S=!0,0;var d,f=0;d=a.parentNode;var e=c.parentNode,h=[a],l=[c];if(!d||!e)return a===b?-1:c===b?1:d?-1:e?1:L?N.call(L,a)-N.call(L,c):0;if(d===e)return g(a,c);for(d=a;d=d.parentNode;)h.unshift(d);for(d=c;d=d.parentNode;)l.unshift(d);for(;h[f]===l[f];)f++;return f?g(h[f],l[f]):h[f]===C?-1:l[f]===
C?1:0};return b};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&J(a);b=b.replace(xa,"='$1']");if(x.matchesSelector&&F&&(!O||!O.test(b))&&(!A||!A.test(b)))try{var d=aa.call(a,b);if(d||x.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(f){}return 0<c(b,z,null,[a]).length};c.contains=function(a,b){(a.ownerDocument||a)!==z&&J(a);return T(a,b)};c.attr=function(a,b){(a.ownerDocument||a)!==z&&J(a);var c=t.attrHandle[b.toLowerCase()],
c=c&&ta.call(t.attrHandle,b.toLowerCase())?c(a,b,!F):void 0;return void 0!==c?c:x.attributes||!F?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var b,c=[],d=0,f=0;S=!x.detectDuplicates;L=!x.sortStable&&a.slice(0);a.sort(fa);if(S){for(;b=a[f++];)b===a[f]&&(d=c.push(f));for(;d--;)a.splice(c[d],1)}L=null;return a};$=c.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=$(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=$(b);return c};t=c.selectors={cacheLength:50,createPseudo:f,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(H,I);a[3]=(a[3]||a[4]||a[5]||"").replace(H,I);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&ya.test(c)&&(b=U(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(H,I).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ja[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ja(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==Q&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===d:"!="===b?
f!==d:"^="===b?d&&0===f.indexOf(d):"*="===b?d&&-1<f.indexOf(d):"$="===b?d&&f.slice(-d.length)===d:"~="===b?-1<(" "+f+" ").indexOf(d):"|="===b?f===d||f.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,f){var e="nth"!==a.slice(0,3),h="last"!==a.slice(-4),l="of-type"===b;return 1===d&&0===f?function(a){return!!a.parentNode}:function(b,c,g){var m,r,v,s,p;c=e!==h?"nextSibling":"previousSibling";var w=b.parentNode,n=l&&b.nodeName.toLowerCase();g=!g&&!l;if(w){if(e){for(;c;){for(r=b;r=r[c];)if(l?r.nodeName.toLowerCase()===
n:1===r.nodeType)return!1;p=c="only"===a&&!p&&"nextSibling"}return!0}p=[h?w.firstChild:w.lastChild];if(h&&g){g=w[y]||(w[y]={});m=g[a]||[];s=m[0]===D&&m[1];v=m[0]===D&&m[2];for(r=s&&w.childNodes[s];r=++s&&r&&r[c]||(v=s=0)||p.pop();)if(1===r.nodeType&&++v&&r===b){g[a]=[D,s,v];break}}else if(g&&(m=(b[y]||(b[y]={}))[a])&&m[0]===D)v=m[1];else for(;r=++s&&r&&r[c]||(v=s=0)||p.pop();)if((l?r.nodeName.toLowerCase()===n:1===r.nodeType)&&++v)if(g&&((r[y]||(r[y]={}))[a]=[D,v]),r===b)break;v-=f;return v===d||
0===v%d&&0<=v/d}}},PSEUDO:function(a,b){var d,e=t.pseudos[a]||t.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return e[y]?e(b):1<e.length?(d=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var d,f=e(a,b),h=f.length;h--;)d=N.call(a,f[h]),a[d]=!(c[d]=f[h])}):function(a){return e(a,0,d)}):e}},pseudos:{not:f(function(a){var b=[],c=[],d=ea(a.replace(Y,"$1"));return d[y]?f(function(a,b,c,f){f=d(a,null,f,[]);for(var e=a.length;e--;)if(c=f[e])a[e]=!(b[e]=c)}):
function(a,f,e){b[0]=a;d(b,null,e,c);return!c.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(H,I);return function(b){return-1<(b.textContent||b.innerText||$(b)).indexOf(a)}}),lang:f(function(a){za.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(H,I).toLowerCase();return function(b){var c;do if(c=F?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===G},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Ba.test(a.nodeName)},input:function(a){return Aa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:w(function(){return[0]}),
last:w(function(a,b){return[b-1]}),eq:w(function(a,b,c){return[0>c?c+b:c]}),even:w(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:w(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:w(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:w(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};t.pseudos.nth=t.pseudos.eq;for(R in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[R]=p(R);for(R in{submit:!0,reset:!0})t.pseudos[R]=n(R);r.prototype=t.filters=
t.pseudos;t.setFilters=new r;U=c.tokenize=function(a,b){var d,f,e,h,g,l,m;if(g=ka[a+" "])return b?0:g.slice(0);g=a;l=[];for(m=t.preFilter;g;){if(!d||(f=va.exec(g)))f&&(g=g.slice(f[0].length)||g),l.push(e=[]);d=!1;if(f=wa.exec(g))d=f.shift(),e.push({value:d,type:f[0].replace(Y," ")}),g=g.slice(d.length);for(h in t.filter)if((f=ba[h].exec(g))&&(!m[h]||(f=m[h](f))))d=f.shift(),e.push({value:d,type:h,matches:f}),g=g.slice(d.length);if(!d)break}return b?g.length:g?c.error(a):ka(a,l).slice(0)};ea=c.compile=
function(a,b){var c,d=[],f=[],e=la[a+" "];if(!e){b||(b=U(a));for(c=b.length;c--;)e=da(b[c]),e[y]?d.push(e):f.push(e);e=la(a,ra(f,d));e.selector=a}return e};ga=c.select=function(a,b,c,d){var f,e,h,g,l="function"===typeof a&&a,m=!d&&U(a=l.selector||a);c=c||[];if(1===m.length){e=m[0]=m[0].slice(0);if(2<e.length&&"ID"===(h=e[0]).type&&x.getById&&9===b.nodeType&&F&&t.relative[e[1].type]){if(b=(t.find.ID(h.matches[0].replace(H,I),b)||[])[0])l&&(b=b.parentNode);else return c;a=a.slice(e.shift().value.length)}for(f=
ba.needsContext.test(a)?0:e.length;f--;){h=e[f];if(t.relative[g=h.type])break;if(g=t.find[g])if(d=g(h.matches[0].replace(H,I),ca.test(e[0].type)&&s(b.parentNode)||b)){e.splice(f,1);a=d.length&&E(e);if(!a)return K.apply(c,d),c;break}}}(l||ea(a,m))(d,b,!F,c,ca.test(a)&&s(b.parentNode)||b);return c};x.sortStable=y.split("").sort(fa).join("")===y;x.detectDuplicates=!!S;J();x.sortDetached=e(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});e(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||l("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!x.attributes||!e(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&l("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});e(function(a){return null==a.getAttribute("disabled")})||l("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof q&&q.amd?q(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,firefox:c.firefox,ie:Boolean(c.msie||c.trident),ios:Boolean(c.applewebkit&&c.mobile),opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie||c.rv||c.firefox)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},
c={contains:function(a,b){return this.regexp(b).test(a)},redact:function(a,b){return a.replace(this.regexp(b),"___")},regexp:function(c){c=b.extend({},c);var f=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,b){return this.contains(a+" "+document.referrer,b||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a=
{NONE:{id:"full",scope:"body",spec:{selector:"body"}},bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},
scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,
selector:"article[class*='post-'], div[id^='post-']"}}},c={getPostId:function(a){var c,e;if(this===b.platforms.NONE)return" ";e=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=e[a]?e[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=
[];!a&&(document&&document.body)&&(a=[document.body]);a&&this.spec&&(c=b.withScope(a,this.spec.selector,{consolidate:!0}));return c}};b.each(a,function(d,e){d.id=d.id||e;b.each(c,function(a,c){d[c]=b.bind(a,d)});a[e]=d});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(b){return b.id===a})};return a}();b.observer=function(){var a,c=[],d=0,e=function(){a||(a=new MutationObserver(b.entryPoint(function(a){var d=[];b.each(a,function(a){var c=[];"characterData"===a.type?
a.target&&(c=[a.target]):"attributes"===a.type?c=[a.target]:a.addedNodes&&a.addedNodes.length&&(c=b.toArray(a.addedNodes));c.length&&(d=d.concat(c))});0<d.length&&b.each(c,function(a){a.callback(d)})})))},h=function(c){var h={attributes:!1,characterData:!1,childList:!1,subtree:!0};d||(e(),c.opts.attributes&&(h=b.extend(h,{attributes:!0}),"array"===b.type(c.opts.attributes)&&(h=b.extend(h,{attributeFilter:c.opts.attributes}))),c.opts.content&&(h=b.extend(h,{characterData:!0,childList:!0})),a.observe(c.context,
h))};return{start:function(a,d,e){a.document&&(a=a.document);d=b.extend({attributes:!1,content:!0},d);b.traits.mutation&&b.contains(["document","element"],b.type(a))&&(a={callback:e,context:a,opts:d},c.push(a),h(a))},pause:function(){d++;a&&a.disconnect()},resume:function(){d--;b.each(c,h)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,fastRegexp:!b.browser.firefox,
json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,performanceTiming:Boolean(window.performance&&window.performance.timing),referrerPolicy:!b.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var g,n,p,u;e={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:function(){var a;
return function(){a||(a=b.generateNodeFilter({classes:["novig"],rels:["novig"],selectors:g.exclude_scope,tags:"applet embed noscript object head img input link meta param select button iframe option script style svg textarea title".split(" ")}));return a.apply(e,arguments)}}(),api:function(){var a,c,d,e=function(){var a={optimize:"content",domains:"content"};return function(c,d,e){var f=b.toArray(arguments).slice(3,arguments.length),h=a[c];Boolean(h)&&(e=b.extend({},e,{json_payload:h}));var h=c,m=
l(e),p;p=b.extend(b.commonParams(c,g),d);p.subId&&p.key!==g.key&&(p.subId=null);return{data:f,method:h,opts:m,params:p}}}(),h=function(a){var c={},d={};b.each(a,function(a){var e=a[0],f=a[1],h=a[2]||{};a=b.toArray(a).slice(3,a.length);d[e]=b.mergeParams(d[e]||b.commonParams(e,g),f);c[e]=c[e]||[];c[e].push({data:a,opts:l(h)})});return{calls:c,params:d}},l=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(d){var e,f=d.response?d.response[0]:null;"object"===b.type(f)&&
("array"===b.type(f.crawl)&&"object"===b.type(u.crawler)&&"function"===b.type(u.crawler.crawl))&&(e=b.map(f.crawl,function(a){return a+""}),delete f.crawl,u.crawler.crawl(e));return c.apply(a,arguments)}}(a.fn));return a},m=function(a){var c=a.opts.base_url||g.api_url,d=a.opts.path||"/"+a.method;delete a.opts.base_url;return b.request.apply(b,[c+d,a.params,a.opts].concat(a.data))},p=function(a,c,d){b.each(c,function(c){c&&(c.opts&&c.opts.fn&&a)&&c.opts.fn({response:b.packageArgs(a),data:c.data,args:d})})};
a=function(){var a=function(a){var c=a.data[0].params,d=a.data[0].calls;a=b.fromJSON(a.response[0])||{};b.each(a,function(a,e){var f=c[e],h=d[e],g;if("string"===b.type(a)&&(g=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(g[1]);p(a,h,f)})};return function(c){c=h(c,!0);m({data:c,method:"batch",params:b.extend(b.commonParams("batch",g),c.params),opts:{json_payload:"batch",jsonp:!1,fn:b.bind(a,window)}})}}();c=function(a,c,d){var g=h(a,!1);a=b.reduce({},g.calls[d],function(a,b){return{jsonp:a.jsonp||
!b.opts||!1!==b.opts.jsonp,ssl:a.ssl||!b.opts||!1!==b.opts.ssl}});return m(e(c,g.params[c],{fn:function(a){p(a.response[0],g.calls[c],g.params[c])},jsonp:a.jsonp,ssl:a.ssl},g))};d=function(){return m(e.apply(this,arguments))};return b.batchable(function(){var e,f;return b.batched(arguments)?(e=b.batchArgs(arguments),f=b.batchCallType(e),"batch"===f?a.call(this,e):c.call(this,e,f)):d.apply(this,arguments)},function(){return{batch:g.batch_calls,timeout:g.batch_call_timeout}})}(),addEventListener:function(a,
b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var e=a.open("",c);e.focus();return e}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],m=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},p=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),
a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?m(c,"previous"):"",g[2]=h&&3===h.nodeType?m(h,"next"):"",g=p.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,
before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),v:2},e.log("info",b.toQuery(a))))};return function(d,e){var h,l,m,p,n={},k=b.context(d)||window;e=d.target||e;e=!e||e===k.name||"_top"===e&&k.top===k||"_parent"===e&&k.parent===k?"_self":e;m=a(k,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))p="go";else try{if(void 0===m.document)throw!0;p="jsonp"}catch(s){p="go"}h=b.destructing(b.apiCallback(function(){g.time_api&&this.logEvent.stop("clk");
var a=b.toArray(arguments);a.unshift(d,m,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!g.enabled)return h();!b.traits.referrerPolicy&&this.isPrivate(d)&&(p="go");l=this.clickParams(d,p);g.time_api&&this.logEvent.start("clk");g.log_context&&c(d);if("go"===p)l=this.redirectUrl(l,n),this.redirect(l,k,m,e);else if(m===k)this.api.now("click",l,b.extend(n,{fn:h,timeout:g.click_timeout}));
else{if(b.contextIsAncestor(k,m))return this.redirect(b.getActualHref(d),k,m,e);h=b.entryPoint(h);setTimeout(function(){h()},g.click_timeout);m.document.open();m.callback=h;m.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",l,b.extend(n,{fn:"callback","return":!0}))+'">\x3c/script></head></html>');m.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,loAsUuid:b.cache(a,"uuid")||null,
out:b.getActualHref(a),reaf:g.reaffiliate||null,ref:window.document.referrer||null,rewrit:b.cache(a,"rewrit"),title:window.document.title,txt:a.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==p||1E3<b?a(0==p&&g):setTimeout(function(){c(a,2*b)},2*b)}function e(){--p||(g=!k&&n)}var g=!1,p=2,k=!1,n=!1;if("function"==
typeof b){a+="?ch=*&rn=*";var s=11*Math.random(),r=new Image;r.onload=e;r.onerror=function(){k=!0;e()};r.src=a.replace(/\*/,1).replace(/\*/,s);r=new Image;r.onload=e;r.onerror=function(){n=!0;e()};r.src=a.replace(/\*/,2).replace(/\*/,s);c(b,250)}}}}catch(c){a={detect:function(a,b){b(!0)}}}return function(c){var e=b.updateUrl(g.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,c)}}(),enabled:function(){if(g.enabled&&p!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))g.enabled=
!1;return g.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!u[a]){var d=u,f;f=c;f="function"===b.type(f)?b.entryPoint(b.bind(f,e)):f;d[a]=f}}}(),fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,c){if(g.rewrite_modified&&
a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.redirectUrl(this.clickParams(a,"go"));setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return g.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;n={};if(a()){try{c.initLibEvents(),c.initNamespace(),
c.initOptions()}catch(d){}b.exceptionLogger(b.bind(c.logException,c),!g.dev);b.each(g.script_timeout);return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);u=p[k]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},
this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("allowed");this.expose("api");this.expose("apiNow",b.bind(this.api.now,this.api));this.expose("harmony");this.expose("isBlacklisted");this.expose("isCommercial");this.expose("opt");this.expose("platform");this.expose("clickParams",function(){return b.extend(b.commonParams("click",g),e.clickParams.apply(e,arguments))});this.expose("registerProcessor",function(){if(0<arguments.length)return e.registerProcessor.apply(e,
arguments)});this.expose("sendLinks");b.extend(u,u===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDomObserver:function(a,c){b.observer.start(a,c,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,b){return a.concat(b)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&e.allowed(a)});0<a.length&&(b.each(b.withScope(a,
"a[href]",{ancestors:!1}),function(a){e.processLinks(a[1])}),b.each(n,function(b,c){b.opts.mode!==e.PLUGIN_MANUAL&&e.runPlugin(c,a)}))},function(){return{batch:g.batch_mutation,timeout:g.batch_mutation_timeout}}))},initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;g.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c=
b.traits.windowLevelHandlers?a:a.document,d=function(c){c=c||a.event;if((c=b.eventLink(c))&&!b.cache(c,"evented"))h(e.EVENT_LEVEL_LINK,c),b.cache(c,"evented",!0)},f=function(a,c){return function(){var d=[a].concat(b.toArray(arguments));c.apply(e,d)}},h=function(a,c){b.on(c,"click",f(a,e.onClick));b.on(c,"contextmenu",f(a,e.onContextmenu))};if(g.dynamic)b.on("DOMReady",function(){e.initDomObserver(a);g.dynamic_scope&&b.each(b.select(g.dynamic_scope,a.document),function(a){e.initDomObserver(a,{attributes:["class",
"id","style"],content:!1})})});b.on(c,"copy",b.bind(e.onCopy,e));b.on(c,"mousedown",d);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",d)})});(!b.traits.quirksMode||e.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&h(e.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(u[b[a]]=window[a],"vglnk_domain"===a&&
(u[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){g.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(e);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(k="vglnk");var a=window,b=k.split("."),d;for(k=
b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];p=a;u=p[k]=p[k]||{}},initOptions:function(){var a;this.initLegacyOptions();g=b.extend(this.publicOptions({anywhere_url:"//redirect.viglink.com",api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,reaffiliate:!1,sub_id:null,sync_url:"//api.viglink.com/api",blacklist_domains:{},commercial_domains:{},harmony_level:b.harmony.DEFAULT,
link_target:null,private_domains:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),g,u,{batch_calls:!0,batch_call_timeout:100,batch_links:!1,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,debug:!1,declare_handler:!1,dynamic:!0,dynamic_scope:null,exclude_scope:null,hop_timeout:2E3,insert_host:"i.viglink.com",library_id:null,links_merge_timeout:75,links_version:3.2,log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,testing_js:[],time_api:!1,time_load:!1,time_log_timeout:3E3,
plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});g.sync_url=g.sync_url||g.api_url;for(a in g)"_plugin"===a.substr(-7)&&delete g[a]},initPlugins:function(){var a,c=1,d={link_affiliation:"convert",link_optimization:"optimize",page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=["spotlight"],h=["harmony"],l=function(b){return function(b){return function(){delete n[b].opts.mode;c=1;clearTimeout(a);p()}}(b)},m=function(a){var c;
b.find(d,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:g.key,link_phrases:!1});a[c].link_urls=g.link_urls;return a},p=function(){var d={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},f=function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,d,a.setup(b.reformatKeys(a.opts),b.clone(b),u,l(g.key))),a["public"]&&e.expose(c,a["public"],!1)),a.opts.mode!==e.PLUGIN_MANUAL&&
e.runPlugin(c))},l=function(a){var c=function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);e.log.apply(this,c)}};c.event=e.logEvent;return c},m=function(a){return!Boolean(a._ran)};a=null;b.each(h,function(a){var b=n[a];b&&!Boolean(b._ran)&&f(b,a)});b.each(b.all(n,m),f);b.find(n,m)&&(a=setTimeout(b.entryPoint(p),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},k=function(){setTimeout(function(){e.api.flush()},100);p();b.on("DOMReady",function(){setTimeout(e.api.flush,0)})};return function(a){a=
m(a);b.each(a,b.bind(function(a,c){c=d[c]||c;"object"===typeof a&&!1!==a.enabled&&(n[c]={opts:a},b.contains(f,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,l(c)))},this));k()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(g.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,
b.cache(a,"params",c))});this.registerProcessor(function(a){g.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){g.declare_handler&&b.attributes(a,{"data-hl":"viglink"})});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isAuctionLink:function(a){return!0===b.cache(a,"auctioned")},
isBlacklisted:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.blacklist_domains)&&g.blacklist_domains[a]},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.commercial_domains)&&g.commercial_domains[a]},isPrivate:function(a){if("array"!==b.type(g.private_domains))return!1;var c=b.canonicalizeHostname(a);return b.find(g.private_domains,function(a){return RegExp("(^|\\.)"+b.escapeRegExp(a)+"$","i").test(c)})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),
c=b.generateNodeFilter({classes:["norewrite"],rels:["norewrite","noskim"],custom:function(c,f){if(!f)return!1;var h=b.canonicalizeHostname(c),l="",m=!1;try{l=c.protocol,h.charAt(0)}catch(p){return!0}m=Boolean(""===h||!l.match(/^https?:$/i)||g.norewrite[h]);if(l=!m)var l=b.cache(c,"type"),k=b.cache(c,"params")||{},l=!Boolean(l||k.type);l&&(m=Boolean(a===h||!g.rewrite_original||!g.rewrite_any&&!e.isCommercial(c)));return m}});return function(a){return c(a)}}(),log:function(a,c,d,e){var h,l=b.toQuery({libId:g.library_id,
nocache:b.uniqid()});h="pixel.gif";if("custom"===a)l+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],function(a){b.each(["e","i","o"],function(b){delete a[b]});l+="&"+b.toQuery(a)});else{l+="&"+b.toQuery({key:g.key,drKey:g.key?null:g.dr_key,subId:g.sub_id});if("time"===a&&b.traits.json)h="time.gif",a={e:b.toJSON(c),v:2};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;l+="&"+b.toQuery(a)}h=g.api_url+"/"+h+"?"+l;b.pii.transmits(h)||(b.createEl("img").src=h)},
logEvent:function(){var a={},c=b.time(),d=b.traits.performanceTiming?window.performance.timing.domLoading:null,f=b.batchable(function(){var a;a=b.batched(arguments)?b.batchArgs(arguments):[arguments];a=b.map(a,function(a){return b.prune({event:a[0],time:a[1],total:a[2]})});a.length&&e.log("time",a)},function(){return{timeout:g.time_log_timeout}});return{start:function(c){a[c]=a[c]||{logged:0,times:[]};a[c].times.push(b.time())},stop:function(c){var e,g,p=b.time();a[c]&&(a[c].times&&a[c].times.length)&&
(e=a[c].times.shift(),g=d&&0===a[c].logged?p-d:null,a[c].logged+=1,f(c,p-e,g))},load:function(){d&&f("load",c-d)}}}(),logException:function(a){if(g.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},onApiClick:function(a,c,d,e,h){var l=e||b.getActualHref(a),m=b.bind(function(){this.redirect(l,b.context(a),c,d)},this);"object"===typeof h&&(h.tracking||h.image)?(e=b.createEl(h.tracking?
"iframe":"img",{src:h.tracking||h.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.entryPoint(m),h.timeout||g.hop_timeout)):m()},onApiPing:function(a,c,d,f,h,l){g.rewrite_original=!1;h=b.reformatKeys(h||{});var m,p;f=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};b.exceptionLogger(function(){b.canonicalizeHostname(window.location).match(/(^|\.)cnn\.com$/)&&(g.exclude_scope="#optanon,.OUTBRAIN,*[class*=outbrain],*[class*=partner],*[class*=sponsored]")})();
b.exceptionLogger(function(){b.canonicalizeHostname(window.location).match(/^(www\.)?msn\.com$/)&&(g.dynamic_scope=".gallery-container > .gallerydata,section.gallery:first-child ~ .gallerydata",g.declare_handler=!0)})();p=b.extend(g.plugins,h.plugins);g=b.extend(g,h);delete g.plugins;g.click_timeout=c;g.library_id=a;h.time&&(g.time_api=g.time_load=h.time);g.time_api&&this.logEvent.stop("png");g.time_load&&this.logEvent.load();"array"===b.type(g.testing_js)&&0<g.testing_js.length&&b.each(g.testing_js,
function(a){b.jsonp(a)});b.extend(g.nofollow,f(l));b.extend(g.norewrite,f(d));for(m in g)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===b.type(g[m]))&&(b.on(e,m.toLowerCase().substr(2),b.bind(g[m],window)),delete g[m]);this.initPlugins(p);this.initContext(window);this.fire("libready")},onClick:function(a,c){c=c||window.event;var d=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,e=c.which&&1===c.which||0===c.button,g=b.eventLink(c);if(g&&e&&!d&&!b.isDefaultPrevented(c)&&this.allowed(g)&&
this.isRewritable(g)&&!this.isAuctionLink(g)&&this.shouldHandleClick(a,g))return this.click(g),b.preventDefault(c)},onContextmenu:function(a,c){var d=b.eventLink(c||window.event);d&&(this.allowed(d)&&this.isRewritable(d)&&!this.isAuctionLink(d)&&this.shouldHandleClick(a,d))&&this.handleRightClick(d,"setup")},onCopy:function(a){var c,d,f,g=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{f=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,
"\n")}catch(l){}0<f.length&&128>=f.length&&g.push(f)}}b.each(g,function(a){e.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(g[a]=b);return g[a]},ping:function(){var a=!1;return function(){if(!a&&(g.key||g.dr_key)){var c={ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logEvent.start("png"),this.detectFiltering(b.bind(function(a){a&&(g.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);
this.api.now("ping",c,{fn:b.apiCallback(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(g.platform)||b.platforms.NONE},processLink:function(a){var c=b.cache(a,"processors")||{},d=this.allowed(a),e=this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(d&&(e||b.opts.any))&&b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===
b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,f){var g=function(a,c,d){var f=[],g;if(b.traits.referrerPolicy){g=function(a){var b=c.document.createElement("meta");b.name="referrer";b.content=a;c.document.getElementsByTagName("head")[0].appendChild(b)};e.isPrivate(a)&&(f=[g("no-referrer"),g("never")]);d();try{b.each(f,function(a){a.parentNode.removeChild(a)})}catch(h){}}else d()};c=c||window.top;!b.traits.crossWindowCommunication&&!d?(f=c.open(a,f),f.focus()):b.traits.jsRedirectSetsReferrer?
setTimeout(b.entryPoint(function(){!d||d===c?g(a,c,function(){c.location=a}):b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===f&&(f=b.uniqid("win_")),f=b.createA(a,f),f.rel="norewrite",c.document.body.appendChild(f),f.click(),f.parentNode.removeChild(f))},redirectUrl:function(a,c){c=c||{};return this.api.now("click",a,b.extend(c,{base_url:g.anywhere_url,path:"/"},{"return":!0}))},runPlugin:function(a,c){var d=window.document,e=n[a];if(e&&e.initDocuments){if(c)e.initNodes(c);
else if(e.init(),"function"===b.type(e.initDocuments)&&"document"===b.type(d)&&e.initDocuments([d]),"function"===b.type(e.initNodes)&&"element"===b.type(d.body))b.on("DOMReady",function(){e.initNodes([d.body])});e._ran=!0}},registerProcessor:function(){var a=!1,c=[],d=function(d,e){if(void 0===d)return c;"function"===b.type(d)&&(e=b.extend({any:!1},e),c.push({fn:d,id:b.uniqid(),opts:e}),a&&this.initLinks())};d(function(){a=!0});return d}(),sendLinks:b.mergeable(function(){return{batchFn:e.api,nonBatchFn:e.api.now,
batchable:g.batch_links,timeout:g.links_merge_timeout}}),shouldHandleClick:function(a,c){var d=!0,e="inserted"===b.cache(c,"type");a===this.EVENT_LEVEL_LINK&&(d=this.harmony(b.harmony.LINK_EVENTS)||(this.isCommercial(c)||e)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return d}};e.init();try{delete window.vglnk_self}catch(B){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(k,e,b){var q={},g,n;k=e.extend({any:!0,convert_minimum_bid:!1,check_exp_domains:!0},k);n={getDomains:function(){var g=[];e.each(q,function(b,e){2!==q[e]&&(g.push(e),q[e]=2)});0<g.length&&b.apiNow("domains",{domains:g.join("|"),v:"2"},{fn:e.apiCallback(n.onDomainApi,n)})},init:function(){b.opt("link_target",k.link_target);b.opt("rewrite_any",k.any);b.opt("rewrite_original",!0);(g=!k.any||b.harmony(e.harmony.COMMERCIAL_LINK_EVENTS)||k.convert_minimum_bid||k.check_exp_domains)&&
b.registerProcessor(e.bind(function(b){this.initDomainLookup();this.saveDomain(b)},this),{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,e.on("DOMReady",e.bind(this.getDomains,this)))}}(),onDomainApi:function(){var g=e.destructing(function(){b.registerProcessor(function(g){b.opt("declare_handler")&&e.attributes(g,{"data-hl":"viglink"})});b.registerProcessor(e.bind(function(b){n.unlinkBlacklisted(b)},this),{any:!0})});return function(k){var n=b.opt("blacklist_domains")||
{},a=b.opt("commercial_domains")||{};e.each(k.results,function(b,d){a[d]=!0;b.unlink&&(n[d]=!0)});b.opt("commercial_domains",a);b.opt("blacklist_domains",n);g()}}(),saveDomain:function(b){b=e.canonicalizeHostname(b);q[b]=q[b]||1},unlinkBlacklisted:function(g){b.isBlacklisted(g)&&e.unlink(g)}};return{init:e.bind(n.init,n),initNodes:function(){n.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(k,e,b){var q=[],g=b.platform();k={crawl:function(b){if(g&&!("array"!==e.type(b)||0===b.length))b=e.all(b,function(b){return!e.contains(q,b)}),b=this.findPostsById(b),e.each(b,e.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=e.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return e.all(e.map(g.getPosts(),function(b){return{el:b,id:g.getPostId(b)}}),
function(g){return e.contains(b,g.id)})},processPosts:function(k){k=e.map(k,function(b){q.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:e.toJSON({ct:k,pt:g.id,u:location.href})},{jsonp:!1})},redact:function(b){return e.pii.redact(b)}};return{"public":{crawl:e.bind(k.crawl,k)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(k,e,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.privacy_plugin=function(k,e,b){return{init:function(){k.domains&&b.opt("private_domains",k.domains)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(k,e,b){k=e.extend({key:null},k);var q={init:function(b){e.each(this.getDRSearchForms(b),function(b){if(!e.cache(b,"evented")){var g=q.getInput(b),k=function(){g.value||e.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};e.cache(b,"evented",!0);b.onsubmit=null;g.onfocus=null;g.onblur=null;e.on(g,"focus",function(){e.css(g,{"background-image":"none"})});e.on(g,"blur",k);k();e.on(b,"submit",function(e){q.onSubmit(e,b)})}})},
getDRSearchForms:function(b){var k=[];e.each(b,function(b){"element"===e.type(b)&&e.each(b.getElementsByTagName("form"),function(b){q.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&k.push(b)})});return k},getInput:function(b){return b.p||b.q2},onSubmit:function(g,n){g=g||window.event;var p="http://shop.ebay.com/i.html?"+e.toQuery({_nkw:q.getInput(n).value}),p=e.createA(p,"_blank");e.cache(p,"params",{key:k.key});b.click(p);return e.preventDefault(g)}};if(k.key)return{init:e.bind(q.init,q),
initNodes:function(b){q.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(k,e,b){k=e.extend({level:e.harmony.DEFAULT},k);return{init:function(){var e=parseFloat(k.level,10);isFinite(e)&&b.opt("harmony_level",e)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(k,e,b,q){var g,n={uuid:"uuid",index:"idx",optimized_url:"url",aliases:"aka"};k=e.extend({scope:"body"},k);g={cache:function(){var b={},e={};return{links:{get:function(e){return b[e]},set:function(e,a){var c={};c[n.optimized_url]=a[n.optimized_url];c[n.uuid]=a[n.uuid];c[n.aliases]=a[n.aliases];b[e]=c}},stats:{increment:function(b,a){e[b]||(e[b]={});if(a)if("rep"===a)e[b].rep=(e[b].rep||0)+1;else{var c;c=e[b].ex=e[b].ex||{};c[a]=(c[a]||0)+1}else e[b].n=(e[b][n.insertion_count]||
0)+1},getAndReset:function(){var b=e;e={};return b}}}}(),filterLinkNodes:function(){var b={sameDomainOrInternal:function(){var b=window.location.hostname;return function(a){return b===a.hostname}}()},k=function(g){return e.all(g,function(a){return e.every(b,function(b){return!b(a)})})};return function(b){var a={needs_optimization:[],needs_call:[]};e.each(k(b),function(b){var d=g.cache.links.get(b.href);d&&d[n.uuid]&&e.cache(b,"uuid",d[n.uuid]);d&&d[n.optimized_url]?a.needs_optimization.push(b):d&&
"false"===d[n.optimized_url]||a.needs_call.push(b)});return a}}(),generateAliases:function(b){var k=[],q=g.cache.links.get(b.href),k=k.concat(q[n.aliases]||[]);k.push(e.canonicalizeHostname(b.href));k.push(e.canonicalizeHostname(q[n.optimized_url]));return e.unique(k)},getLinks:function(k){b.opt("time_api")&&q.event.start("opt");b.sendLinks("optimize",{links:e.unique(e.map(k,function(b){return b.href})),mode:["O"],u:location.href,ver:b.opt("links_version")},{fn:e.bind(g.onOptimizeApi,g)},k)},log:e.batchable(function(){var b=
{stats:e.toJSON(g.cache.stats.getAndReset())};4<b.stats.length&&q("loJsLog",b)},function(){return{timeout:1E3}}),onOptimizeApi:function(k){var u=k.response[0],B=k.args.links,a=k.data[0];b.opt("time_api")&&q.event.stop("opt");"object"===e.type(u)&&(k=["opt","non","unk"],e.each(k,function(a){u[a]&&u[a].length&&e.each(u[a],function(b){var e=B[b[n.index]];"non"===a&&(b[n.optimized_url]=!1);g.cache.links.set(e,b)})}),k=g.filterLinkNodes(a),g.optimizeLinks(k.needs_optimization))},optimizeLinks:function(b){e.each(b,
function(b){e.cache(b,"rewrit",!1)});b=g.runExclusionFilters(b);e.each(b,this.optimizeLink);e.traits.json&&g.log()},optimizeLink:function(){var b=function(a){return a.replace(/^https?:\/\//,"")},q=function(a,b){for(var d;d=a.firstChild;)a.removeChild(d);a.appendChild(document.createTextNode(b))},B=function(a){var c=a.href,d=a.textContent||a.innerText,f=Boolean(d),h=g.generateAliases(a),l=function(){var a=b(c).toLowerCase(),f=d.toLowerCase().replace(a,"");return e.some(h,function(a){return-1!==f.indexOf(a.toLowerCase())})},
k=function(){var a=d.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+e.map(a,e.escapeRegExp).join(".+")+"$").test(c)},n=function(){var b=e.canonicalizeHostname(a);return e.canonicalizeHostname(e.createEl("a",{href:d}))===b},q=function(){var b;return n()?(b=e.fromQuery(a.search),e.find(b,function(a){return a===d})):!1};return{full_replace:Boolean(f&&(c===d||b(c)===d||k()||q())),exclude:Boolean(f&&l()),partial_replace:Boolean(f&&(-1!==d.indexOf(c)||-1!==d.indexOf(b(c))))}};return function(a){var c,
d=g.cache.links.get(a.href),f=d[n.optimized_url];c=B(a);if(f&&!k.observer){if(c.full_replace)q(a,f),g.cache.stats.increment(d[n.uuid],"rep");else{if(c.exclude){g.cache.stats.increment(d[n.uuid],"a");return}c.partial_replace&&(c="undefined"!==e.type(a.textContent)?a.textContent:a.innerText,c=-1!==c.indexOf(a.href)?c.replace(a.href,f):c.replace(b(a.href),f),q(a,c),g.cache.stats.increment(d[n.uuid],"rep"))}f=-1===f.indexOf("http://")?"http://"+f:f;a.href=f}g.cache.stats.increment(d[n.uuid]);e.cache(a,
"rewrit",!0)}}(),runExclusionFilters:function(){var k=e.generateNodeFilter({classes:["nooptimize","norewrite"],rels:["nooptimize","norewrite","noskim"],custom:function(a,b){if(b)return Boolean(e.cache(a,"type"))}}),q=function(a){var b=g.generateAliases(a),d=e.context(a).document.title;return e.every(b,function(a){return-1===d.indexOf(a)})},B=function(){var a=function(a,b){var c=e.reduce([],["prev_tokens","next_tokens"],function(b,c){a[c]&&a[c].length&&(b=b.concat(a[c]));return b}).join(" ").toLowerCase();
return e.some(b,function(a){return-1!==c.indexOf(a.toLowerCase())})},b=function(){var a=function(a){a="undefined"!==e.type(a.textContent)?a.textContent:a.innerText;return e.all(a.split(/\s+/g),function(a){return""!==a})};return function(b){for(var c={prev_tokens:[],next_tokens:[]};b&&b!==document.body.parentNode;){for(var g=c,k=b.previousSibling,n=b.nextSibling;k||n;)k&&(e.nodesOfType([k],1,3).length&&"SCRIPT"!==k.tagName)&&(g.prev_tokens=g.prev_tokens.concat(a(k).reverse())),k=!k?!1:k.previousSibling,
n&&(e.nodesOfType([n],1,3).length&&"SCRIPT"!==n.tagName)&&(g.next_tokens=g.next_tokens.concat(a(n))),n=!n?!1:n.nextSibling;if(20<c.prev_tokens.length+c.next_tokens.length+0)break;b=b.parentNode}return c}}();return function(d){var e=g.generateAliases(d);d=b(d);80<d.prev_tokens.length+d.next_tokens.length+0&&(d.prev_tokens=d.prev_tokens.slice(0,40),d.next_tokens=d.next_tokens.slice(0,40));d.prev_tokens=d.prev_tokens.reverse();return!a(d,e)}}();return function(a){return e.all(a,function(a){var d=g.cache.links.get(a.href)[n.uuid];
if(!b.allowed(a)||!k(a))return g.cache.stats.increment(d,"n"),!1;if(B(a)){if(!q(a))return g.cache.stats.increment(d,"t"),!1}else return g.cache.stats.increment(d,"p"),!1;return!0})}}()};return{initNodes:function(n){var q;n=e.nodesOfType(n,1);n=e.all(e.links(n,k.scope),b.allowed);n=g.filterLinkNodes(n);(q=n.needs_optimization)&&q.length&&g.optimizeLinks(q);(n=n.needs_call)&&n.length&&g.getLinks(n)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(k,e,b,q){var g,n,p,u,B=null,a=null;k=e.extend({cat:null,dynamic_sample_rate:1,insertion_order:"api",key:null,link_phrases:!0,link_target:null,link_urls:!0,manual_mode:1===k.mode,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},k);"api"!==k.insertion_order&&"dom"!==k.insertion_order&&(k.insertion_order="api");if(k.key)return g=b.platform(),n={cache:function(){var a,b,f=function(){a={};b={}},g=function(f,g){var h,k=b,l=a,m={};g=g||[e.platforms.DEFAULT_POST_ID];
h=e.all(e.unique(e.map(g,function(a){return k[a]})),function(a){return null!==a});e.find(h,function(a){if(l[a]&&l[a].data&&l[a].order){if(f)return m[f]=l[a].data[f],!0;e.each(l[a].order,function(b){var c=l[a].data[b];m[b]||(m[b]=c)})}});return f?m[f]:m},l=function(f,g,h,k){var l=a,m=b;h=h||"-";k=k||[e.platforms.DEFAULT_POST_ID];l[h]=l[h]||{data:{},order:[]};l[h].data[f]||(l[h].data[f]=g,l[h].order.push(f));e.each(k,function(a){m[a]=h});return!0},m=function(a,b,c,d){var f=e.all(e.toArray(arguments),
function(a){return Boolean(a)});"array"===e.type(f[f.length-1])&&(d=f.pop());a=f[0];b=f[1];if(1>=f.length)return g(a,d);if(2<=f.length)return l(a,b,c,d)};k.manual_mode&&e.extend(m,{reset:f});f();return m}(),enabled:function(){return k.link_phrases||k.link_urls},focusLink:function(a){a.id||(a.id=e.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,d,e=b.opt("partner"),g={};for(a in e)break;if(a)for(d in e[a])g[a+"_"+d]=e[a][d];return g},getPhrases:function(a,
d){b.opt("time_api")&&q.event.start("ins");b.api("insert",e.extend(n.getPartnerParams(),{cat:k.cat,i:d?d.join("|"):null,mode:k.mode,pt:g.id,ps:k.product_source,u:location.href}),{fn:e.apiCallback(n.onInsertApi,n)},a,d)},hasCalled:function(){var a={},b=Math.random()<k.dynamic_sample_rate,f=function(a){return b&&e.isArray(a)?e.map(a,function(a){return f(a)}):b&&a===e.platforms.DEFAULT_POST_ID?location.href:a},g=function(b){b=f(b);return e.isArray(b)&&b.length?Boolean(e.all(b,function(b){return a[b]}).length===
b.length):Boolean(a[e.platforms.DEFAULT_POST_ID])},l=function(b){b=f(b);e.isArray(b)&&b.length?e.each(b,function(b){a[b]=!0}):a[e.platforms.DEFAULT_POST_ID]=!0};return function(a,b){return b?l(a):g(a)}}(),init:function(){k.scope=k.scope||g.scope;k.link_urls&&(u=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com\\b/?)(?!\\.[a-z0-9-]+))",
"i"))},initLink:function(){return function(a,d,f){var g=k.link_target;if(g="U"===d.type?b.opt("link_target"):g||f)a.target=g;a.href||(a.href=d.url);a.rel="nofollow";e.cache(a,"params",{exp:B,iid:d.iid,key:k.key,mid:d.mid,type:d.type||null});if(!0===d.auc){d=e.fromQuery(a.search);if(f=d.u||d.out)delete d.format,delete d.out,delete d.u,e.extend(d,b.clickParams(a),{out:f}),a.search="?"+e.toQuery(d);e.cache(a,"auctioned",!0)}e.cache(a,"href",a.href);b.link(a)}}(),insertLinks:function(){var a=e.generateNodeFilter({classes:["nolinks",
"atma-nolink","atma-nolinks"],tags:["map"],custom:function(a){return e.matches(a,"a")&&Boolean(a.href)}}),d=function(a,b,c,d){var l={phrase_to_nodes:{},regexp_cache:{},stats:{}};e.each(b,function(b){g(a,b,c,d,l)},{timeout:!0});"api"===k.insertion_order&&f(c,l);return l.stats},f=function(a,b){var c=m(a);c.push("&!UNLINKED!&");e.each(c,function(c){(c=b.phrase_to_nodes[c])&&e.each(c,function(c){q(c,c.data,a,b)})})},g=function(d,e,f,k,m){if(b.allowed(e)&&a(e,{ancestors:!Boolean(k),self:!0}))if(3===e.nodeType)l(d,
e,f,m);else if(1===e.nodeType)for(e=e.firstChild;e;)k=e.nextSibling,g(d,e,f,!0,m),e=k},l=function(){var a=function(a,b){var c=[];e.each(a,function(a){var d;b[a]?d=b[a]:(d=e.escapeRegExp(a).split(" ").join("\\s+"),d=RegExp("(?:^|[\\s\"'\\(])("+d+")(?=\\s|\\W*$|\\W{2})","i"),b[a]=d);c.push(d)});k.link_urls&&u&&c.push(u);return c},b=function(a,b){var c=m(b);a=n.normalizePhrase(a);return e.all(c,function(b){return-1!==a.indexOf(b)})};return function(c,d,f,g){var h,l,m=!1,q=g.phrase_to_nodes,x=g.regexp_cache;
d.parentNode&&(d.data&&(m=c.test(d.data.replace(/\s+/," "))),m&&"dom"===k.insertion_order?p(c,d,f,g):m&&"api"===k.insertion_order&&(h=b(d.data,f),c=a(h,x),l=[d],e.each(c,function(a){var b=[];e.each(l,function(c){for(var d,f,g,k,l;c&&(c.data&&""!==c.data&&(Boolean(!e.traits.fastRegexp&&(g=c.data.match(/^\s+/)))||Boolean(g=c.data.match(a))))&&g.input!==d;){d=g.input;f=g.slice(1).join("");if(!f)break;k=n.normalizePhrase(f);f=w(c,g);f.previous&&f.previous.data&&b.push(f.previous);c=f.next;l=e.contains(h,
k)?k:"&!UNLINKED!&";k=q;f=f.match;k[l]||(k[l]=[]);k[l].push(f)}c&&!g&&b.push(c)},{timeout:!0});l=b})))}}(),m=function(a){a=n.cache(a);return e.map(a,function(a,b){return b})},p=function(a,b,c,d){for(var f,g,h;b&&(b.data&&""!==b.data&&(Boolean(!e.traits.fastRegexp&&(h=b.data.match(/^\s+/)))||Boolean(h=b.data.match(a))))&&h.input!==f;){f=h.input;g=h.slice(1).join("");if(!g)break;b=w(b,h);q(b.match,g,c,d);b=b.next}},q=function(){var a=function(a,b){var c,d;c=!a||!k.per_phrase||!b[a.phrase]||b[a.phrase].count<
k.per_phrase;d=!k.per_page||e.reduce(0,b,function(a,b){return a+b.count})<k.per_page;return c&&d},c=function(a,c,d){var f,g=Boolean(b.opt("dynamic_scope")),h=function(){var b,c;if(!d.phrase)return!0;if(k.proximity||k.same_proximity)c=e.geometry(f),e.find(n.cache(a),function(a){var f,g;if(a.links){if((f=n.normalizePhrase(a.phrase)===n.normalizePhrase(d.phrase))&&!k.same_proximity||!f&&!k.proximity)return!1;g=f?Math.max(k.same_proximity,k.proximity):k.proximity;a.links=e.all(a.links,function(a){var d=
e.isInDom(a.el);!b&&d&&(b=e.find(a.segments,function(a){a=a.geometry;a=e.extend({},a);a.x1-=g;a.y1-=g;a.x2+=g;a.y2+=g;if(a.x1<c.x2&&a.x2>c.x1&&a.y1<c.y2&&a.y2>c.y1)return!0}));return d});return b}});return!b};if(!c.parentNode)return!1;f=e.createEl("span");c.parentNode.insertBefore(f,c);f.appendChild(c);return function(a){f.parentNode.insertBefore(c,f);f.parentNode.removeChild(f);return a}((!g||e.isVisible(f))&&h())};return function(d,f,g,h){var l;h=h.stats;var m=n.normalizePhrase(f),m=f?n.cache(m,
g):null;f&&!m&&(m={url:f.match(/^https?:\/\//i)?f:"http://"+f,type:"U"});if(m&&m.url.match(/https?:\/\//i)&&f&&a(m,h)&&c(g,d,m)){var p=m;g=e.createEl("a");g.innerHTML=f.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");g.className="vglnk";e.cache(g,"type","inserted");e.cache(g,"phrase",f);k.ui&&"U"!==p.type&&(g.title="Link added by VigLink");n.initLink(g,p);if(!e.cache(g,"unlinked")&&!b.isBlacklisted(g)){f=d.parentNode;f.insertBefore(g,d);f.removeChild(d);d=m;var q;f={el:g,segments:[]};var u=
g.getElementsByTagName("span"),t={els:[]};g=0;for(p=u.length;g<p;g++)q=u[g],void 0===l||q.offsetTop===l.offsetTop?t.els.push(q):(f.segments.push(t),t={els:[q]}),l=q;t.geometry=e.geometry.apply(e,t.els);f.segments.push(t);d.links=d.links||[];d.links.push(f);l=m.phrase||m.url;h[l]=h[l]||{count:0,iid:m.iid,phrase:m.phrase,type:m.type};h[l].count++}}}}(),w=function(a,b){var c,d;d=b.slice(1).join("");c=b.index+b[0].length-d.length;0<c?c=a.splitText(c):(c=a,a=null);d=c.length<=d.length?null:c.splitText(d.length);
return{previous:a,match:c,next:d}};return function(b,f){var g={},h=n.regexp(f);h&&((b=e.all(b,a))&&b.length&&(g=d(h,b,f,!1)),k.link_phrases&&n.log(g))}}(),insertManually:function(){var a=!1,b=e.clone(k),f=function(a){return e.map(a,function(a,b){return{iid:"00000000",phrase:b,type:"0",url:a}})};return function(g,l,m){var q,u=!1;p.init();k.manual_mode&&!a&&(a=!0,q=l=l||{},k.same_proximity=q.same_proximity||k.same_proximity,k.proximity=q.proximity||k.proximity,k.per_page=q.per_page||k.per_page,k.per_phrase=
q.per_phrase||k.per_phrase,q=l.target_node||document.body,g=f(g),n.loadPhrases(g,null,[q]),k=b,n.cache.reset(),u=!0,a=!1);"function"===e.type(m)&&m(u,q)}}(),loadPhrases:function(a,b,f,g){e.each(a,function(a){a.phrase&&(a.url&&a.iid)&&(a.phrase=n.normalizePhrase(a.phrase),n.cache(a.phrase,{auc:a.auc,count:0,iid:a.iid,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},b,g))});n.hasCalled(g,!0);this.insertLinks(f,g)},log:function(b){var d=0,f=0,g=[];e.each(b,function(a,b){var c=parseInt(a.count,10);
0<c&&("U"===a.type?f+=c:"0"!==a.type&&g.push({count:c,iid:a.iid,phrase:b,type:a.type}),d+=c)});0<d&&q("insert",[{ct:d,cl:f,exp:B,imp_id:a,phrases:e.toJSON(g)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},onInsertApi:function(c,d,f){b.opt("time_api")&&q.event.stop("ins");"object"===e.type(c)&&(B=c.exp,a=c.imp_id,c.results&&this.loadPhrases(c.results,a,d,f))},regexp:function(a){var b;a=n.cache(a);a=e.map(a,function(a,b){return e.escapeRegExp(b).split(" ").join("\\s+")});
0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(u?"(?:"+b+"|"+u.source+")":b,"i"));return b||u}},p={init:e.destructing(e.bind(n.init,n)),initNodes:function(a){var d=[],f=[],h=[];n.enabled()&&(k.scope?(e.each(a,function(a){var b=e.withScope([a],k.scope,{ancestors:!0,consolidate:!0,descendants:!1,self:!0});b.length?(h.push(a),f=f.concat(b)):(a=e.withScope([a],k.scope,{ancestors:!1,consolidate:!0,descendants:!0,self:!1}),a.length&&(h=h.concat(a),f=f.concat(a)))},{timeout:!0}),
h=e.unique(h),f=e.unique(f)):f=h=a,Boolean(b.opt("dynamic_scope"))&&(h=e.all(h,function(a){return!e.matches(a,":has(a.vglnk)")},{timeout:!0})),h.length&&(f.length&&(d=g.getPostIds(f)),k.link_phrases&&!n.hasCalled(d)?n.getPhrases(h,d):n.insertLinks(h,d)))}},k.manual_mode&&e.extend(p,{"public":{run:n.insertManually}}),p};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(k,e,b){var q;k=e.extend({log_links:!0,log_status:!1,pai_type:[],scope:"body"},k);q={extractDescription:function(){var b;b=window.document.getElementsByTagName("meta");return(b=e.find(b,function(b){return b.getAttribute("name")&&"description"===b.getAttribute("name").toLowerCase()}))?b.getAttribute("content")||null:null},logViews:function(g,k){var p={links:e.unique(e.map(g,function(b){return b.href})),mode:["P"],u:location.href,ver:b.opt("links_version"),title:window.document.title};
k&&(p.desc=k);b.sendLinks("optimize",p,{jsonp:!1})},logStatus:function(g){e.createEl("img").src=e.updateUrl(b.opt("sync_url"),{pathname:"/api/sync/status.gif",search:"?"+e.toQuery({st:g})})},run:function(){var b=k.pai_type;e.isArray(b)&&b.length&&q.sync(b)},sync:function(){return function(g){var n,p;n=g.shift();p=e.updateUrl(b.opt("sync_url"),{pathname:"/api/sync.gif",search:"?"+e.toQuery({partner_id:n})});n=e.createEl("img");e.on(n,"load",function(){k.log_status&&q.logStatus("su");g.length&&q.sync(g)});
e.on(n,"error",function(){k.log_status&&q.logStatus("fa");g.length&&q.sync(g)});k.log_status&&q.logStatus("bg");n.src=p}}()};return{init:function(){q.run()},initNodes:function(g){k.log_links&&(g=e.links(g,k.scope),g=e.all(g,b.allowed),g.length&&q.logViews(g,q.extractDescription()))}}};
